// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveChallenge struct {
	ChannelID       string
	Kind            string
	ChallengeID     *string
	ChallengeValue  *string
	ChallengeSeed   *string
	IssuedAt        pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	ConsumedAt      pgtype.Timestamptz
	CommitTokenMode *string
}

type Channel struct {
	Uuid                string
	State               string
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	TtlMs               int64
	SecurityProfile     string
	AdminMode           *string
	AdminCredential     []byte
	LockKey             *string
	ReceiverPubJwk      []byte
	ReceiverPubFpr      *string
	LockedAt            pgtype.Timestamptz
	CipherBundle        []byte
	FileRef             []byte
	UpdateDeliveryProof []byte
	DeliveredAt         pgtype.Timestamptz
	Version             int64
}

type ServiceMetadatum struct {
	MetadataKey   string
	MetadataValue string
	CreatedAt     pgtype.Timestamptz
}

type TerminalTombstone struct {
	ChannelID   string
	Reason      string
	FinalizedAt pgtype.Timestamptz
}

type UsedNonce struct {
	ChannelID string
	Nonce     string
	UsedAt    pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
