// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireChannelAdvisoryLock = `-- name: AcquireChannelAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireChannelAdvisoryLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, acquireChannelAdvisoryLock, pgAdvisoryXactLock)
	return err
}

const deleteActiveChallenge = `-- name: DeleteActiveChallenge :exec
DELETE FROM active_challenges
WHERE channel_id = $1
  AND kind = $2
`

type DeleteActiveChallengeParams struct {
	ChannelID string
	Kind      string
}

func (q *Queries) DeleteActiveChallenge(ctx context.Context, arg DeleteActiveChallengeParams) error {
	_, err := q.db.Exec(ctx, deleteActiveChallenge, arg.ChannelID, arg.Kind)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE uuid = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, uuid string) error {
	_, err := q.db.Exec(ctx, deleteChannel, uuid)
	return err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM active_challenges
WHERE expires_at IS NOT NULL
  AND expires_at <= $1
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredUsedNonces = `-- name: DeleteExpiredUsedNonces :execrows
DELETE FROM used_nonces
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredUsedNonces(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUsedNonces, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUsedNonce = `-- name: DeleteUsedNonce :exec
DELETE FROM used_nonces
WHERE channel_id = $1
  AND nonce = $2
`

type DeleteUsedNonceParams struct {
	ChannelID string
	Nonce     string
}

func (q *Queries) DeleteUsedNonce(ctx context.Context, arg DeleteUsedNonceParams) error {
	_, err := q.db.Exec(ctx, deleteUsedNonce, arg.ChannelID, arg.Nonce)
	return err
}

const getActiveChallenge = `-- name: GetActiveChallenge :one
SELECT
  channel_id,
  kind,
  challenge_id,
  challenge_value,
  challenge_seed,
  issued_at,
  expires_at,
  consumed_at,
  commit_token_mode
FROM active_challenges
WHERE channel_id = $1
  AND kind = $2
LIMIT 1
`

type GetActiveChallengeParams struct {
	ChannelID string
	Kind      string
}

func (q *Queries) GetActiveChallenge(ctx context.Context, arg GetActiveChallengeParams) (ActiveChallenge, error) {
	row := q.db.QueryRow(ctx, getActiveChallenge, arg.ChannelID, arg.Kind)
	var i ActiveChallenge
	err := row.Scan(
		&i.ChannelID,
		&i.Kind,
		&i.ChallengeID,
		&i.ChallengeValue,
		&i.ChallengeSeed,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CommitTokenMode,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT
  uuid,
  state,
  created_at,
  expires_at,
  ttl_ms,
  security_profile,
  admin_mode,
  admin_credential,
  lock_key,
  receiver_pub_jwk,
  receiver_pub_fpr,
  locked_at,
  cipher_bundle,
  update_delivery_proof,
  delivered_at,
  version
FROM channels
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetChannel(ctx context.Context, uuid string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, uuid)
	var i Channel
	err := row.Scan(
		&i.Uuid,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TtlMs,
		&i.SecurityProfile,
		&i.AdminMode,
		&i.AdminCredential,
		&i.LockKey,
		&i.ReceiverPubJwk,
		&i.ReceiverPubFpr,
		&i.LockedAt,
		&i.CipherBundle,
		&i.UpdateDeliveryProof,
		&i.DeliveredAt,
		&i.Version,
	)
	return i, err
}

const getTerminalTombstone = `-- name: GetTerminalTombstone :one
SELECT
  channel_id,
  reason,
  finalized_at
FROM terminal_tombstones
WHERE channel_id = $1
LIMIT 1
`

func (q *Queries) GetTerminalTombstone(ctx context.Context, channelID string) (TerminalTombstone, error) {
	row := q.db.QueryRow(ctx, getTerminalTombstone, channelID)
	var i TerminalTombstone
	err := row.Scan(&i.ChannelID, &i.Reason, &i.FinalizedAt)
	return i, err
}

const getUsedNonce = `-- name: GetUsedNonce :one
SELECT
  channel_id,
  nonce,
  used_at,
  expires_at
FROM used_nonces
WHERE channel_id = $1
  AND nonce = $2
LIMIT 1
`

type GetUsedNonceParams struct {
	ChannelID string
	Nonce     string
}

func (q *Queries) GetUsedNonce(ctx context.Context, arg GetUsedNonceParams) (UsedNonce, error) {
	row := q.db.QueryRow(ctx, getUsedNonce, arg.ChannelID, arg.Nonce)
	var i UsedNonce
	err := row.Scan(
		&i.ChannelID,
		&i.Nonce,
		&i.UsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markChallengeConsumed = `-- name: MarkChallengeConsumed :one
UPDATE active_challenges
SET consumed_at = $3
WHERE channel_id = $1
  AND kind = $2
RETURNING
  channel_id,
  kind,
  challenge_id,
  challenge_value,
  challenge_seed,
  issued_at,
  expires_at,
  consumed_at,
  commit_token_mode
`

type MarkChallengeConsumedParams struct {
	ChannelID  string
	Kind       string
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) MarkChallengeConsumed(ctx context.Context, arg MarkChallengeConsumedParams) (ActiveChallenge, error) {
	row := q.db.QueryRow(ctx, markChallengeConsumed, arg.ChannelID, arg.Kind, arg.ConsumedAt)
	var i ActiveChallenge
	err := row.Scan(
		&i.ChannelID,
		&i.Kind,
		&i.ChallengeID,
		&i.ChallengeValue,
		&i.ChallengeSeed,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CommitTokenMode,
	)
	return i, err
}

const upsertActiveChallenge = `-- name: UpsertActiveChallenge :one
INSERT INTO active_challenges (
  channel_id,
  kind,
  challenge_id,
  challenge_value,
  challenge_seed,
  issued_at,
  expires_at,
  consumed_at,
  commit_token_mode
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (channel_id, kind) DO UPDATE SET
  challenge_id = EXCLUDED.challenge_id,
  challenge_value = EXCLUDED.challenge_value,
  challenge_seed = EXCLUDED.challenge_seed,
  issued_at = EXCLUDED.issued_at,
  expires_at = EXCLUDED.expires_at,
  consumed_at = EXCLUDED.consumed_at,
  commit_token_mode = EXCLUDED.commit_token_mode
RETURNING
  channel_id,
  kind,
  challenge_id,
  challenge_value,
  challenge_seed,
  issued_at,
  expires_at,
  consumed_at,
  commit_token_mode
`

type UpsertActiveChallengeParams struct {
	ChannelID       string
	Kind            string
	ChallengeID     *string
	ChallengeValue  *string
	ChallengeSeed   *string
	IssuedAt        pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	ConsumedAt      pgtype.Timestamptz
	CommitTokenMode *string
}

func (q *Queries) UpsertActiveChallenge(ctx context.Context, arg UpsertActiveChallengeParams) (ActiveChallenge, error) {
	row := q.db.QueryRow(ctx, upsertActiveChallenge,
		arg.ChannelID,
		arg.Kind,
		arg.ChallengeID,
		arg.ChallengeValue,
		arg.ChallengeSeed,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.CommitTokenMode,
	)
	var i ActiveChallenge
	err := row.Scan(
		&i.ChannelID,
		&i.Kind,
		&i.ChallengeID,
		&i.ChallengeValue,
		&i.ChallengeSeed,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CommitTokenMode,
	)
	return i, err
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (
  uuid,
  state,
  created_at,
  expires_at,
  ttl_ms,
  security_profile,
  admin_mode,
  admin_credential,
  lock_key,
  receiver_pub_jwk,
  receiver_pub_fpr,
  locked_at,
  cipher_bundle,
  update_delivery_proof,
  delivered_at,
  version
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
ON CONFLICT (uuid) DO UPDATE SET
  state = EXCLUDED.state,
  created_at = EXCLUDED.created_at,
  expires_at = EXCLUDED.expires_at,
  ttl_ms = EXCLUDED.ttl_ms,
  security_profile = EXCLUDED.security_profile,
  admin_mode = EXCLUDED.admin_mode,
  admin_credential = EXCLUDED.admin_credential,
  lock_key = EXCLUDED.lock_key,
  receiver_pub_jwk = EXCLUDED.receiver_pub_jwk,
  receiver_pub_fpr = EXCLUDED.receiver_pub_fpr,
  locked_at = EXCLUDED.locked_at,
  cipher_bundle = EXCLUDED.cipher_bundle,
  update_delivery_proof = EXCLUDED.update_delivery_proof,
  delivered_at = EXCLUDED.delivered_at,
  version = EXCLUDED.version
RETURNING
  uuid,
  state,
  created_at,
  expires_at,
  ttl_ms,
  security_profile,
  admin_mode,
  admin_credential,
  lock_key,
  receiver_pub_jwk,
  receiver_pub_fpr,
  locked_at,
  cipher_bundle,
  update_delivery_proof,
  delivered_at,
  version
`

type UpsertChannelParams struct {
	Uuid                string
	State               string
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	TtlMs               int64
	SecurityProfile     string
	AdminMode           *string
	AdminCredential     []byte
	LockKey             *string
	ReceiverPubJwk      []byte
	ReceiverPubFpr      *string
	LockedAt            pgtype.Timestamptz
	CipherBundle        []byte
	UpdateDeliveryProof []byte
	DeliveredAt         pgtype.Timestamptz
	Version             int64
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.Uuid,
		arg.State,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.TtlMs,
		arg.SecurityProfile,
		arg.AdminMode,
		arg.AdminCredential,
		arg.LockKey,
		arg.ReceiverPubJwk,
		arg.ReceiverPubFpr,
		arg.LockedAt,
		arg.CipherBundle,
		arg.UpdateDeliveryProof,
		arg.DeliveredAt,
		arg.Version,
	)
	var i Channel
	err := row.Scan(
		&i.Uuid,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TtlMs,
		&i.SecurityProfile,
		&i.AdminMode,
		&i.AdminCredential,
		&i.LockKey,
		&i.ReceiverPubJwk,
		&i.ReceiverPubFpr,
		&i.LockedAt,
		&i.CipherBundle,
		&i.UpdateDeliveryProof,
		&i.DeliveredAt,
		&i.Version,
	)
	return i, err
}

const upsertTerminalTombstone = `-- name: UpsertTerminalTombstone :one
INSERT INTO terminal_tombstones (
  channel_id,
  reason,
  finalized_at
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (channel_id) DO UPDATE SET
  reason = EXCLUDED.reason,
  finalized_at = EXCLUDED.finalized_at
RETURNING
  channel_id,
  reason,
  finalized_at
`

type UpsertTerminalTombstoneParams struct {
	ChannelID   string
	Reason      string
	FinalizedAt pgtype.Timestamptz
}

func (q *Queries) UpsertTerminalTombstone(ctx context.Context, arg UpsertTerminalTombstoneParams) (TerminalTombstone, error) {
	row := q.db.QueryRow(ctx, upsertTerminalTombstone, arg.ChannelID, arg.Reason, arg.FinalizedAt)
	var i TerminalTombstone
	err := row.Scan(&i.ChannelID, &i.Reason, &i.FinalizedAt)
	return i, err
}

const upsertUsedNonce = `-- name: UpsertUsedNonce :one
INSERT INTO used_nonces (
  channel_id,
  nonce,
  used_at,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (channel_id, nonce) DO UPDATE SET
  used_at = EXCLUDED.used_at,
  expires_at = EXCLUDED.expires_at
RETURNING
  channel_id,
  nonce,
  used_at,
  expires_at
`

type UpsertUsedNonceParams struct {
	ChannelID string
	Nonce     string
	UsedAt    pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertUsedNonce(ctx context.Context, arg UpsertUsedNonceParams) (UsedNonce, error) {
	row := q.db.QueryRow(ctx, upsertUsedNonce,
		arg.ChannelID,
		arg.Nonce,
		arg.UsedAt,
		arg.ExpiresAt,
	)
	var i UsedNonce
	err := row.Scan(
		&i.ChannelID,
		&i.Nonce,
		&i.UsedAt,
		&i.ExpiresAt,
	)
	return i, err
}
